
public enum ComplainDialogStates {
	COMPLAIN_SEND,
	COMPLAIN_DIALOG_STARTED,
	REQUESTED_PLACE,
	REQUESTED_REASON,
	REQUESTED_LINE,
	REQUESTED_DIRECTION,
	REQUESTED_TIME,
	REQUESTED_DATE,
	REQUESTED_STATION,
	REQUESTED_MESSAGE,
	NO_COMPLAIN_DIALOG_IN_USE
}
